project:
  type: book

book:
  title: "Population Science"
  author: "Francisco Rowe, Carmen Cabrera-Arnau, Elisabetta Pietrostefani"

  author-meta: "Francisco Rowe, Carmen Cabrera-Arnau, Elisabetta Pietrostefani"
  date-meta: today

  description-meta: |
    This book will...

  page-footer:
    left: |
      Population Science was written by Francisco Rowe,
      Carmen Cabrera-Arnau, Elisabetta Pietrostefani.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.

  search: true
  site-url: https://www.population-science.net
  repo-url: https://github.com/fcorowe/r4ps
  repo-actions: [edit]
  sharing: [twitter, facebook]
  twitter-card:
    creator: "@fcorowe"
  sidebar:
    style: docked
    background: light
  date: "01/10/2022"
  downloads: [pdf, epub]
  cover-image: source-dall-e.png
  cover-image-alt: |
    Alternative text describing the book cover
  chapters:
    - index.qmd
    - intro.qmd
    - privacy.qmd
    - geodemographics.qmd
    - sequence-analysis.qmd
    - network.qmd
    - sentiment-analysis.qmd
    - topic-modelling.qmd
    - longitudinal-1.qmd
    - longitudinal-2.qmd
    - machine-learning.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: ember.scss
    css: styles.css
  pdf:
    documentclass: scrreprt

editor: visual

