project:
  type: book

book:
  title: "Population Science"
  author: "Francisco Rowe"
  search: true
  sidebar:
    style: docked
    background: light
  date: "01/10/2022"
  downloads: [pdf, epub]
  chapters:
    - index.qmd
    - intro.qmd
    - privacy.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

