<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Population Science - 11&nbsp; Data sets</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./references.html" rel="next">
<link href="./machine-learning.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./data-sets.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Data sets</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Population Science</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/fcorowe/r4ps" rel="" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Download" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Download"><i class="bi bi-download"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./Population-Science.pdf">
              <i class="bi bi-bi-file-pdf pe-1"></i>
            Download PDF
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./Population-Science.epub">
              <i class="bi bi-bi-journal pe-1"></i>
            Download ePub
            </a>
          </li>
      </ul>
    </div>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-1" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-1">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
              <i class="bi bi-bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
      </ul>
    </div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Overview</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro-population-science.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introducing Population Science</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./geodemographics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Geodemographics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sequence-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Sequence Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./network.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Network Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sentiment-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Sentiment Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./topic-modelling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Topic Modelling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./longitudinal-1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Modelling Time</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./longitudinal-2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Assessing Interventions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./machine-learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Machine Learning</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-sets.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Data sets</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#greater-machester-land-use-data" id="toc-greater-machester-land-use-data" class="nav-link active" data-scroll-target="#greater-machester-land-use-data"><span class="header-section-number">11.1</span> Greater Machester land use data</a>
  <ul class="collapse">
  <li><a href="#availability" id="toc-availability" class="nav-link" data-scroll-target="#availability">Availability</a></li>
  <li><a href="#variables" id="toc-variables" class="nav-link" data-scroll-target="#variables">Variables</a></li>
  <li><a href="#source-pre-processing" id="toc-source-pre-processing" class="nav-link" data-scroll-target="#source-pre-processing">Source &amp; Pre-processing</a></li>
  </ul></li>
  <li><a href="#british-administrative-boundaries-lsoas-and-las" id="toc-british-administrative-boundaries-lsoas-and-las" class="nav-link" data-scroll-target="#british-administrative-boundaries-lsoas-and-las"><span class="header-section-number">11.2</span> British administrative boundaries (LSOAs and LAs)</a>
  <ul class="collapse">
  <li><a href="#availability-1" id="toc-availability-1" class="nav-link" data-scroll-target="#availability-1">Availability</a></li>
  <li><a href="#variables-1" id="toc-variables-1" class="nav-link" data-scroll-target="#variables-1">Variables</a></li>
  <li><a href="#projection" id="toc-projection" class="nav-link" data-scroll-target="#projection">Projection</a></li>
  <li><a href="#source-pre-processing-1" id="toc-source-pre-processing-1" class="nav-link" data-scroll-target="#source-pre-processing-1">Source &amp; Pre-processing</a></li>
  </ul></li>
  <li><a href="#worldpop-population-count-data-for-ukraine" id="toc-worldpop-population-count-data-for-ukraine" class="nav-link" data-scroll-target="#worldpop-population-count-data-for-ukraine"><span class="header-section-number">11.3</span> Worldpop population count data for Ukraine</a></li>
  <li><a href="#census-population-count-data-for-uk" id="toc-census-population-count-data-for-uk" class="nav-link" data-scroll-target="#census-population-count-data-for-uk"><span class="header-section-number">11.4</span> Census population count data for UK</a></li>
  <li><a href="#ukraines-administrative-boundaries" id="toc-ukraines-administrative-boundaries" class="nav-link" data-scroll-target="#ukraines-administrative-boundaries"><span class="header-section-number">11.5</span> Ukraine’s administrative boundaries</a></li>
  <li><a href="#internal-migration-flows-between-us-metropolitan-areas-and-between-london-boroughs" id="toc-internal-migration-flows-between-us-metropolitan-areas-and-between-london-boroughs" class="nav-link" data-scroll-target="#internal-migration-flows-between-us-metropolitan-areas-and-between-london-boroughs"><span class="header-section-number">11.6</span> Internal migration flows between US metropolitan areas and between London boroughs</a>
  <ul class="collapse">
  <li><a href="#availability-2" id="toc-availability-2" class="nav-link" data-scroll-target="#availability-2">Availability</a></li>
  <li><a href="#variables-2" id="toc-variables-2" class="nav-link" data-scroll-target="#variables-2">Variables</a></li>
  <li><a href="#source-pre-processing-2" id="toc-source-pre-processing-2" class="nav-link" data-scroll-target="#source-pre-processing-2">Source &amp; pre-processing</a></li>
  </ul></li>
  <li><a href="#twitter-data-on-public-opinion-originated-in-the-us-and-in-the-uk" id="toc-twitter-data-on-public-opinion-originated-in-the-us-and-in-the-uk" class="nav-link" data-scroll-target="#twitter-data-on-public-opinion-originated-in-the-us-and-in-the-uk"><span class="header-section-number">11.7</span> Twitter data on public opinion originated in the US and in the UK</a></li>
  <li><a href="#reddit-data" id="toc-reddit-data" class="nav-link" data-scroll-target="#reddit-data"><span class="header-section-number">11.8</span> Reddit data</a>
  <ul class="collapse">
  <li><a href="#availability-3" id="toc-availability-3" class="nav-link" data-scroll-target="#availability-3"><span class="header-section-number">11.8.1</span> Availability</a></li>
  <li><a href="#variables-3" id="toc-variables-3" class="nav-link" data-scroll-target="#variables-3"><span class="header-section-number">11.8.2</span> Variables</a></li>
  <li><a href="#source-pre-processing-3" id="toc-source-pre-processing-3" class="nav-link" data-scroll-target="#source-pre-processing-3"><span class="header-section-number">11.8.3</span> Source &amp; Pre-processing</a></li>
  </ul></li>
  <li><a href="#google-mobility-data-for-italy-and-the-uk" id="toc-google-mobility-data-for-italy-and-the-uk" class="nav-link" data-scroll-target="#google-mobility-data-for-italy-and-the-uk"><span class="header-section-number">11.9</span> Google mobility data for Italy and the UK</a>
  <ul class="collapse">
  <li><a href="#availability-4" id="toc-availability-4" class="nav-link" data-scroll-target="#availability-4"><span class="header-section-number">11.9.1</span> Availability</a></li>
  <li><a href="#variables-4" id="toc-variables-4" class="nav-link" data-scroll-target="#variables-4"><span class="header-section-number">11.9.2</span> Variables</a></li>
  </ul></li>
  <li><a href="#covid-19-cases-data-for-london-and-rome" id="toc-covid-19-cases-data-for-london-and-rome" class="nav-link" data-scroll-target="#covid-19-cases-data-for-london-and-rome"><span class="header-section-number">11.10</span> COVID-19 cases data for London and Rome</a>
  <ul class="collapse">
  <li><a href="#availability-5" id="toc-availability-5" class="nav-link" data-scroll-target="#availability-5"><span class="header-section-number">11.10.1</span> Availability</a></li>
  <li><a href="#variables-5" id="toc-variables-5" class="nav-link" data-scroll-target="#variables-5"><span class="header-section-number">11.10.2</span> Variables</a></li>
  </ul></li>
  <li><a href="#census-msoa-data-for-england-and-wales" id="toc-census-msoa-data-for-england-and-wales" class="nav-link" data-scroll-target="#census-msoa-data-for-england-and-wales"><span class="header-section-number">11.11</span> Census MSOA data for England and Wales</a>
  <ul class="collapse">
  <li><a href="#availability-6" id="toc-availability-6" class="nav-link" data-scroll-target="#availability-6">Availability</a></li>
  <li><a href="#variables-6" id="toc-variables-6" class="nav-link" data-scroll-target="#variables-6">Variables</a></li>
  <li><a href="#source-pre-processing-4" id="toc-source-pre-processing-4" class="nav-link" data-scroll-target="#source-pre-processing-4">Source &amp; pre-processing</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/fcorowe/r4ps/edit/main/data-sets.qmd" class="toc-action">Edit this page</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-chp11" class="quarto-section-identifier"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Data sets</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="greater-machester-land-use-data" class="level2" data-number="11.1">
<h2 data-number="11.1" class="anchored" data-anchor-id="greater-machester-land-use-data"><span class="header-section-number">11.1</span> Greater Machester land use data</h2>
<section id="availability" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="availability">Availability</h3>
<p>The dataset is stored on a gpkg file that can be found, within the structure of this project, under:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>st_LSOA <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">"./data/geodemographics/manchester_land_cover_2011.gpkg"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `manchester_land_cover_2011' from data source 
  `/Users/PIETROST/Library/CloudStorage/Dropbox/GitHub/r4ps/data/geodemographics/manchester_land_cover_2011.gpkg' 
  using driver `GPKG'
Simple feature collection with 1673 features and 44 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 351662.3 ymin: 381166 xmax: 406087.2 ymax: 421037.7
Projected CRS: OSGB36 / British National Grid</code></pre>
</div>
</div>
</section>
<section id="variables" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="variables">Variables</h3>
<p>The variables included in this dataset follow the land use classification of the CORINE Land Cover dataset.</p>
</section>
<section id="source-pre-processing" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="source-pre-processing">Source &amp; Pre-processing</h3>
<p>The data was sourced from <a href="https://github.com/GDSL-UL/APPG-LBA/blob/main/README.md">What do ‘left behind’ areas look like over time?</a> and cleaned on Python.</p>
</section>
</section>
<section id="british-administrative-boundaries-lsoas-and-las" class="level2" data-number="11.2">
<h2 data-number="11.2" class="anchored" data-anchor-id="british-administrative-boundaries-lsoas-and-las"><span class="header-section-number">11.2</span> British administrative boundaries (LSOAs and LAs)</h2>
<section id="availability-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="availability-1">Availability</h3>
<p>The dataset for the boundaries of the lower-layer super-output areas (LSOAs) within London is stored as a shapefile that can be found under:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>st_LSOA <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">"data/geodemographics-old/LSOA_2011_London_gen_MHW/LSOA_2011_London_gen_MHW.shp"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `LSOA_2011_London_gen_MHW' from data source 
  `/Users/PIETROST/Library/CloudStorage/Dropbox/GitHub/r4ps/data/geodemographics-old/LSOA_2011_London_gen_MHW/LSOA_2011_London_gen_MHW.shp' 
  using driver `ESRI Shapefile'
Simple feature collection with 4835 features and 14 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 503574.2 ymin: 155850.8 xmax: 561956.7 ymax: 200933.6
Projected CRS: OSGB36 / British National Grid</code></pre>
</div>
</div>
<p>The dataset for the boundaries of the local authority distrits (LADs) for the UK is stored as a shapefile that can be found under:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>LA_UK <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">"./data/networks/Local_Authority_Districts_(December_2022)_Boundaries_UK_BFC/LAD_DEC_2022_UK_BFC.shp"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `LAD_DEC_2022_UK_BFC' from data source 
  `/Users/PIETROST/Library/CloudStorage/Dropbox/GitHub/r4ps/data/networks/Local_Authority_Districts_(December_2022)_Boundaries_UK_BFC/LAD_DEC_2022_UK_BFC.shp' 
  using driver `ESRI Shapefile'
Simple feature collection with 374 features and 10 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: -116.1928 ymin: 5336.966 xmax: 655653.8 ymax: 1220302
Projected CRS: OSGB36 / British National Grid</code></pre>
</div>
</div>
</section>
<section id="variables-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="variables-1">Variables</h3>
<p>For each of the 4,835 LSOAs, the following characteristics are available:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(st_LSOA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "LSOA11CD"  "LSOA11NM"  "MSOA11CD"  "MSOA11NM"  "LAD11CD"   "LAD11NM"  
 [7] "RGN11CD"   "RGN11NM"   "USUALRES"  "HHOLDRES"  "COMESTRES" "POPDEN"   
[13] "HHOLDS"    "AVHHOLDSZ" "geometry" </code></pre>
</div>
</div>
<p>where:</p>
<ul>
<li><code>LSOA11CD</code>: Lower-Layer Super-Output Area code</li>
<li><code>LSOA11NM</code>: Lower-Layer Super-Output Area code</li>
<li><code>MSOA11CD</code>: Medium-Layer Super-Output Area code</li>
<li><code>MSOA11NM</code>: Medium-Layer Super-Output Area code</li>
<li><code>LAD11CD</code>: Local Authority District code</li>
<li><code>LAD11NM</code>: Local Authority District name</li>
<li><code>RGN11CD</code>: Region code</li>
<li><code>RGN11NM</code>: Region name</li>
<li><code>USUALRES</code>: Usual residents</li>
<li><code>HHOLDRES</code>: Household residents</li>
<li><code>COMESTRES</code>: Communal Establishment residents</li>
<li><code>POPDEN</code>: Population density</li>
<li><code>HHOLDS</code>: Number of households</li>
<li><code>AVHHOLDSZ</code>: Average household size</li>
<li><code>geometry</code>: Polygon of LSOA</li>
</ul>
<p>For each of the 374 LADs, the following characteristics are available:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(LA_UK)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "OBJECTID"   "LAD22CD"    "LAD22NM"    "BNG_E"      "BNG_N"     
 [6] "LONG"       "LAT"        "GlobalID"   "SHAPE_Leng" "SHAPE_Area"
[11] "geometry"  </code></pre>
</div>
</div>
<p>where:</p>
<ul>
<li><code>OBJECTID</code>: object identifier</li>
<li><code>LAD22CD</code>: Local Authority District code</li>
<li><code>LAD22NM</code>: Local Authority District name</li>
<li><code>BNG_E</code>: Location Easting</li>
<li><code>BNG_N</code>: Location Northing</li>
<li><code>LONG</code>: Location Longitude</li>
<li><code>LAT</code>: Location Latitude</li>
<li><code>GlobalID</code>: Global Identifier</li>
<li><code>SHAPE_Leng</code>: Boundary length</li>
<li><code>SHAPE_Area</code>: Area within boundary</li>
<li><code>geometry</code>: Polygon of LAD</li>
</ul>
</section>
<section id="projection" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="projection">Projection</h3>
<p>The shapes of each LSOA are stored as polygons an expressed in the OSGB36 projection:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(st_LSOA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: OSGB36 / British National Grid 
  wkt:
PROJCRS["OSGB36 / British National Grid",
    BASEGEOGCRS["OSGB36",
        DATUM["Ordnance Survey of Great Britain 1936",
            ELLIPSOID["Airy 1830",6377563.396,299.3249646,
                LENGTHUNIT["metre",1]],
            ID["EPSG",6277]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["Degree",0.0174532925199433]]],
    CONVERSION["unnamed",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",49,
            ANGLEUNIT["Degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",-2,
            ANGLEUNIT["Degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.999601272,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",400000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",-100000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]]</code></pre>
</div>
</div>
<p>Similarly, the shapes of each LAD are stored as polygons an expressed in the OSGB36 projection:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(LA_UK)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: OSGB36 / British National Grid 
  wkt:
PROJCRS["OSGB36 / British National Grid",
    BASEGEOGCRS["OSGB36",
        DATUM["Ordnance Survey of Great Britain 1936",
            ELLIPSOID["Airy 1830",6377563.396,299.3249646,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4277]],
    CONVERSION["British National Grid",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",49,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",-2,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996012717,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",400000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",-100000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Engineering survey, topographic mapping."],
        AREA["United Kingdom (UK) - offshore to boundary of UKCS within 49°45'N to 61°N and 9°W to 2°E; onshore Great Britain (England, Wales and Scotland). Isle of Man onshore."],
        BBOX[49.75,-9,61.01,2.01]],
    ID["EPSG",27700]]</code></pre>
</div>
</div>
</section>
<section id="source-pre-processing-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="source-pre-processing-1">Source &amp; Pre-processing</h3>
<p>The boundaries for the LSOAs within London can be found directly from the <a href="https://data.london.gov.uk/dataset/statistical-gis-boundary-files-london">London Datastore</a> website.</p>
<p>The boundaries for the LADs for the UK can be found on the ONS Open Geography Portal <a href="https://geoportal.statistics.gov.uk/search?collection=Dataset&amp;sort=name&amp;tags=all(BDY_LAD%2CDEC_2022)">website</a>. To filter for the London LADs, i.e.&nbsp;the London boroughs, we run the following line of code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>LND_boroughs <span class="ot">&lt;-</span> LA_UK <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">grepl</span>(<span class="st">'E09'</span>, LAD22CD)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="worldpop-population-count-data-for-ukraine" class="level2" data-number="11.3">
<h2 data-number="11.3" class="anchored" data-anchor-id="worldpop-population-count-data-for-ukraine"><span class="header-section-number">11.3</span> Worldpop population count data for Ukraine</h2>
</section>
<section id="census-population-count-data-for-uk" class="level2" data-number="11.4">
<h2 data-number="11.4" class="anchored" data-anchor-id="census-population-count-data-for-uk"><span class="header-section-number">11.4</span> Census population count data for UK</h2>
</section>
<section id="ukraines-administrative-boundaries" class="level2" data-number="11.5">
<h2 data-number="11.5" class="anchored" data-anchor-id="ukraines-administrative-boundaries"><span class="header-section-number">11.5</span> Ukraine’s administrative boundaries</h2>
</section>
<section id="internal-migration-flows-between-us-metropolitan-areas-and-between-london-boroughs" class="level2" data-number="11.6">
<h2 data-number="11.6" class="anchored" data-anchor-id="internal-migration-flows-between-us-metropolitan-areas-and-between-london-boroughs"><span class="header-section-number">11.6</span> Internal migration flows between US metropolitan areas and between London boroughs</h2>
<section id="availability-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="availability-2">Availability</h3>
<p>The dataset for the migration flows between US metropolitan areas can be found as a csv file under:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>df_metro <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"./data/networks/metro_to_metro_2015_2019_US_migration.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The dataset for the migration flows between London boroughs can be found as a csv file under:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>df_borough <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"./data/networks/LA_to_LA_2019_London_clean.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="variables-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="variables-2">Variables</h3>
<p>For each of the 52,930 movements recorded on the dataset for the migration flows between US metropolitan areas, the following fields are available:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(df_metro)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "MSA_Current_Code"                                
 [2] "MSA_Current_Name"                                
 [3] "MSA_Current_State"                               
 [4] "MSA_Current_Population_1_Year_and_Over_Estimate" 
 [5] "MSA_Current_Population_1_Year_and_Over_MOE"      
 [6] "MSA_Previous_Code"                               
 [7] "MSA_Previous_Name"                               
 [8] "MSA_Previous_State"                              
 [9] "MSA_Previous_Population_1_Year_and_Over_Estimate"
[10] "MSA_Previous_Population_1_Year_and_Over_MOE"     
[11] "Movers_Metro_to_Metro_Flow_Estimate"             
[12] "Movers_Metro_to_Metro_Flow_MOE"                  </code></pre>
</div>
</div>
<p>All the fields that start with <code>MSA_Current_</code> or <code>MSA_Previous_</code> refer to the characteristics of the origin and destination metropolican areas. The relevant fields for the analysis in this book are:</p>
<ul>
<li><code>Movers_Metro_to_Metro_Flow_Estimate</code>: Estimate of number of people moving between origin and destination</li>
<li><code>Movers_Metro_to_Metro_Flow_MOE</code>: Margin of error for the above estimate</li>
</ul>
<p>More details on the methodology to obtain the estimates and the margin of error for each population movement can be found on the <a href="https://www.census.gov/programs-surveys/acs/methodology.html">US Census Bureau website</a>.</p>
<p>For each of the 1,053 movements recorded on the dataset for the migration flows between London boroughs, the following fields are available:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(df_borough)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "OutLA" "InLA"  "Moves"</code></pre>
</div>
</div>
<p>where:</p>
<ul>
<li><code>OutLA</code> is the code corresponding to the origin borough</li>
<li><code>InLA</code> is the code corresponding to the destination borough</li>
<li><code>Moves</code> is the number of internal migration moves within each flow. Note that the numbers are not integers. This is because of the various scaling processes used to produce the dataset, which are described in more detail in the latest methodology document, which can be found <a href="https://www.ons.gov.uk/peoplepopulationandcommunity/populationandmigration/migrationwithintheuk/datasets/internalmigrationbyoriginanddestinationlocalauthoritiessexandsingleyearofagedetailedestimatesdataset">here</a>.</li>
</ul>
</section>
<section id="source-pre-processing-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="source-pre-processing-2">Source &amp; pre-processing</h3>
<p>The dataset for the migration flows between US metropolitan areas can be downloaded from the <a href="https://www.census.gov/data/tables/2019/demo/geographic-mobility/metro-to-metro-migration.html">US Census Bureau website</a>. The data was cleaned on Microsoft Excel.</p>
<p>The dataset for the migration flows between London boroughs can be downloaded from the <a href="https://www.ons.gov.uk/peoplepopulationandcommunity/populationandmigration/migrationwithintheuk/datasets/internalmigrationbyoriginanddestinationlocalauthoritiessexandsingleyearofagedetailedestimatesdataset">ONS website</a>. The data was cleaned on Microsoft Excel.</p>
</section>
</section>
<section id="twitter-data-on-public-opinion-originated-in-the-us-and-in-the-uk" class="level2" data-number="11.7">
<h2 data-number="11.7" class="anchored" data-anchor-id="twitter-data-on-public-opinion-originated-in-the-us-and-in-the-uk"><span class="header-section-number">11.7</span> Twitter data on public opinion originated in the US and in the UK</h2>
</section>
<section id="reddit-data" class="level2" data-number="11.8">
<h2 data-number="11.8" class="anchored" data-anchor-id="reddit-data"><span class="header-section-number">11.8</span> Reddit data</h2>
<section id="availability-3" class="level3" data-number="11.8.1">
<h3 data-number="11.8.1" class="anchored" data-anchor-id="availability-3"><span class="header-section-number">11.8.1</span> Availability</h3>
<p>Reddit is a social news website where you can find posts about almost anything. Reddit also has a plug-n-play R package which makes is very easy to get Reddit data via API. Everyone can source their own Reddit data. The data used on fertility rates during the pandemic can be accessed through the following code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>comments <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/topic-modelling/comments.csv"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="variables-3" class="level3" data-number="11.8.2">
<h3 data-number="11.8.2" class="anchored" data-anchor-id="variables-3"><span class="header-section-number">11.8.2</span> Variables</h3>
<p>For each of the 78,065 comments from Reddit, the following fields are available:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(comments)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "url"        "author"     "date"       "timestamp"  "score"     
 [6] "upvotes"    "downvotes"  "golds"      "comment"    "comment_id"</code></pre>
</div>
</div>
</section>
<section id="source-pre-processing-3" class="level3" data-number="11.8.3">
<h3 data-number="11.8.3" class="anchored" data-anchor-id="source-pre-processing-3"><span class="header-section-number">11.8.3</span> Source &amp; Pre-processing</h3>
<p>More information on Reddit data and the Reedit API can be found <a href="https://rpubs.com/mswofford/redditAPI">here</a>. Some considerable pre-processing needs to happen to create a Corpus style object using <code>tidytext</code> as shown in <a href="https://www.population-science.net/topic-modelling">Chapter 7</a>. Sme insights on using Reddit data for research <a href="https://journals.sagepub.com/doi/10.1177/20563051211019004">here</a>.</p>
</section>
</section>
<section id="google-mobility-data-for-italy-and-the-uk" class="level2" data-number="11.9">
<h2 data-number="11.9" class="anchored" data-anchor-id="google-mobility-data-for-italy-and-the-uk"><span class="header-section-number">11.9</span> Google mobility data for Italy and the UK</h2>
<section id="availability-4" class="level3" data-number="11.9.1">
<h3 data-number="11.9.1" class="anchored" data-anchor-id="availability-4"><span class="header-section-number">11.9.1</span> Availability</h3>
<p><a href="https://www.google.com/covid19/mobility/">COVID-19 community mobility reports</a> area all freely accessible online.</p>
<p>To access mobility reports for Italy directly, you can the load the following:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>mobility_it <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/longitudinal-1/2022_IT_Region_Mobility_Report.csv"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To access mobility reports for the UK directly, you can the load the following:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>mobility_gb <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/longitudinal-1/2021_GB_Region_Mobility_Report.csv"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The datasets for the geographic boundaries can be load the following for Italy:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>italy_iso3166 <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">"data/longitudinal-1/italy_projected_simplified.geojson"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `italy_projected_simplified' from data source 
  `/Users/PIETROST/Library/CloudStorage/Dropbox/GitHub/r4ps/data/longitudinal-1/italy_projected_simplified.geojson' 
  using driver `GeoJSON'
Simple feature collection with 124 features and 4 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 1313364 ymin: 3933695 xmax: 2312062 ymax: 5220353
Projected CRS: Monte Mario / Italy zone 1</code></pre>
</div>
</div>
<p>With the following CRS:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(italy_iso3166)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: Monte Mario / Italy zone 1 
  wkt:
PROJCRS["Monte Mario / Italy zone 1",
    BASEGEOGCRS["Monte Mario",
        DATUM["Monte Mario",
            ELLIPSOID["International 1924",6378388,297,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4265]],
    CONVERSION["Italy zone 1",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",9,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",1500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["easting (X)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["northing (Y)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Engineering survey, topographic mapping."],
        AREA["Italy - onshore and offshore - west of 12°E."],
        BBOX[36.53,5.93,47.04,12]],
    ID["EPSG",3003]]</code></pre>
</div>
</div>
<p>and this for the UK</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>uk_iso3166 <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">"data/longitudinal-1/uk_projected_simplified.geojson"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `uk_projected_simplified' from data source 
  `/Users/PIETROST/Library/CloudStorage/Dropbox/GitHub/r4ps/data/longitudinal-1/uk_projected_simplified.geojson' 
  using driver `GeoJSON'
Simple feature collection with 245 features and 4 fields (with 16 geometries empty)
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: -50462.93 ymin: 5270.466 xmax: 655975.3 ymax: 1219809
Projected CRS: OSGB36 / British National Grid</code></pre>
</div>
</div>
<p>With the following CRS:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(uk_iso3166)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: OSGB36 / British National Grid 
  wkt:
PROJCRS["OSGB36 / British National Grid",
    BASEGEOGCRS["OSGB36",
        DATUM["Ordnance Survey of Great Britain 1936",
            ELLIPSOID["Airy 1830",6377563.396,299.3249646,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4277]],
    CONVERSION["British National Grid",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",49,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",-2,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996012717,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",400000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",-100000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Engineering survey, topographic mapping."],
        AREA["United Kingdom (UK) - offshore to boundary of UKCS within 49°45'N to 61°N and 9°W to 2°E; onshore Great Britain (England, Wales and Scotland). Isle of Man onshore."],
        BBOX[49.75,-9,61.01,2.01]],
    ID["EPSG",27700]]</code></pre>
</div>
</div>
</section>
<section id="variables-4" class="level3" data-number="11.9.2">
<h3 data-number="11.9.2" class="anchored" data-anchor-id="variables-4"><span class="header-section-number">11.9.2</span> Variables</h3>
<p>The following variables are available.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(mobility_it)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "country_region_code"                               
 [2] "country_region"                                    
 [3] "sub_region_1"                                      
 [4] "sub_region_2"                                      
 [5] "metro_area"                                        
 [6] "iso_3166_2_code"                                   
 [7] "census_fips_code"                                  
 [8] "place_id"                                          
 [9] "date"                                              
[10] "retail_and_recreation_percent_change_from_baseline"
[11] "grocery_and_pharmacy_percent_change_from_baseline" 
[12] "parks_percent_change_from_baseline"                
[13] "transit_stations_percent_change_from_baseline"     
[14] "workplaces_percent_change_from_baseline"           
[15] "residential_percent_change_from_baseline"          </code></pre>
</div>
</div>
<ul>
<li><strong>Grocery &amp; pharmacy</strong> - Mobility trends for places like grocery markets, food warehouses, farmers markets, specialty food shops, drug stores, and pharmacies.</li>
<li><strong>Parks Mobility</strong> - trends for places like local parks, national parks, public beaches, marinas, dog parks, plazas, and public gardens.</li>
<li><strong>Transit stations</strong> - Mobility trends for places like public transport hubs such as subway, bus, and train stations.</li>
<li><strong>Retail &amp; recreation</strong> - Mobility trends for places like restaurants, cafes, shopping centers, theme parks, museums, libraries, and movie theaters.</li>
<li><strong>Residential Mobility</strong> - trends for places of residence.</li>
<li><strong>Workplaces Mobility</strong> - trends for places of work.</li>
</ul>
</section>
</section>
<section id="covid-19-cases-data-for-london-and-rome" class="level2" data-number="11.10">
<h2 data-number="11.10" class="anchored" data-anchor-id="covid-19-cases-data-for-london-and-rome"><span class="header-section-number">11.10</span> COVID-19 cases data for London and Rome</h2>
<section id="availability-5" class="level3" data-number="11.10.1">
<h3 data-number="11.10.1" class="anchored" data-anchor-id="availability-5"><span class="header-section-number">11.10.1</span> Availability</h3>
<p>COVID-19 case data can be downloaded for the UK through the <a href="https://coronavirus.data.gov.uk/details/download">corovirus data portal</a>.</p>
<p>Data for London was pre-prepared for the book and can be accessed here:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>covid_cases_london <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/longitudinal-2/covid_cases_london.csv"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>COVID-19 case data can be downloaded for the Italy through the Presidenza del Consiglio dei Ministri - Dipartimento della Protezione Civile <a href="https://github.com/pcm-dpc/COVID-19/tree/master/dati-province">github</a>.</p>
<p>Data for the Lazio region was pre-prepared for the book and can be accessed here:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>covid_cases_lazio <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/longitudinal-2/covid_cases_lazio.csv"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="variables-5" class="level3" data-number="11.10.2">
<h3 data-number="11.10.2" class="anchored" data-anchor-id="variables-5"><span class="header-section-number">11.10.2</span> Variables</h3>
<p>For each of the 34,229 observations in the London datasets, the following characteristics are available.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(covid_cases_london)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "areaType"                       "areaName"                      
 [3] "areaCode"                       "date"                          
 [5] "newCasesBySpecimenDate"         "cumCasesBySpecimenDate"        
 [7] "newFirstEpisodesBySpecimenDate" "cumFirstEpisodesBySpecimenDate"
 [9] "newReinfectionsBySpecimenDate"  "cumReinfectionsBySpecimenDate" </code></pre>
</div>
</div>
<p>We consider <code>cumCasesBySpecimenDate</code> the cumulative cases equivalent to the total cases present in the Italian data.</p>
<p>For each of the 15,793 observations in the Lazio datasets, the following characteristics are available.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(covid_cases_lazio)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "data"                    "stato"                  
 [3] "codice_regione"          "denominazione_regione"  
 [5] "codice_provincia"        "denominazione_provincia"
 [7] "sigla_provincia"         "lat"                    
 [9] "long"                    "totale_casi"            </code></pre>
</div>
</div>
<ul>
<li><strong>data</strong> - Date and time</li>
<li><strong>stato</strong> - Country</li>
<li><strong>codice_regione</strong> - Regional Code</li>
<li><strong>denominazione_regione</strong> - Region</li>
<li><strong>codice_provincia</strong> - Provincial Code</li>
<li><strong>denominazione_provincia</strong> - Province (sub-region)</li>
<li><strong>totale_casi</strong> - Total number of cases</li>
</ul>
</section>
</section>
<section id="census-msoa-data-for-england-and-wales" class="level2" data-number="11.11">
<h2 data-number="11.11" class="anchored" data-anchor-id="census-msoa-data-for-england-and-wales"><span class="header-section-number">11.11</span> Census MSOA data for England and Wales</h2>
<section id="availability-6" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="availability-6">Availability</h3>
<p>The dataset for the demographic census data of each MSOA in England and Wales can be loaded as a csv file from:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>df_MSOA <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"./data/machine-learning/census2021-msoa-income.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>A very similar dataset for the demographic census data of each MSOA in England and Wales which also contains data on the median house price can be loaded as a csv file from:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>df_housing <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"./data/machine-learning/census2021-msoa-houseprice.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="variables-6" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="variables-6">Variables</h3>
<p>For each of the 7,080 MSOAs recorded in England and Wales, the following fields are available:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(df_MSOA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "X"                "date"             "geography"        "geography.code"  
 [5] "inHH"             "inCE"             "SING"             "MARRIED"         
 [9] "SEP"              "DIV"              "WIDOW"            "UK"              
[13] "EU"               "AFR"              "AS"               "AM"              
[17] "OC"               "BO"               "DENSITY"          "Y14orUNDER"      
[21] "Y15to19"          "Y20to24"          "Y25to29"          "Y30to34"         
[25] "Y35to49"          "Y40to44"          "Y45to49"          "Y50to54"         
[29] "Y55to59"          "Y60to64"          "Y65orOVER"        "F"               
[33] "M"                "HH1"              "HH2"              "HH3"             
[37] "HH4"              "HH5"              "HH6"              "ADD1YagoSAME"    
[41] "ADD1YagoSTUDENT"  "ADD1YagoUK"       "ADD1YagoNONUK"    "NHH"             
[45] "OWN"              "MORTGAGE"         "SHAREDOWN"        "RENTfromCOUNCIL" 
[49] "RENTotherSOCIAL"  "RENTprivate"      "RENTprivateOTHER" "RENTfree"        
[53] "INCOME"          </code></pre>
</div>
</div>
<p>For a description of the variables in the columns of df_MSOA, we can load a dictionary for these variables:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>df_dictionary <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"./data/machine-learning/Dictionary.csv"</span>)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df_dictionary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                      Dictionary       X
1                                                       
2                                           Name     Key
3                 Lives in household (% persons)    inHH
4    Lives in communal establishment (% persons)    inCE
5 Never married or civil partnership (% persons)    SING
6    Married or in civil partnership (% persons) MARRIED</code></pre>
</div>
</div>
</section>
<section id="source-pre-processing-4" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="source-pre-processing-4">Source &amp; pre-processing</h3>
<p>Data on the the census characteristics for different MSOAs can be downloaded from the <a href="https://www.nomisweb.co.uk/census/2021/bulk">Nomis website</a>. Data on the average net household income can be obtained from the <a href="https://www.ons.gov.uk/employmentandlabourmarket/peopleinwork/earningsandworkinghours/datasets/smallareaincomeestimatesformiddlelayersuperoutputareasenglandandwales">ONS website</a>.</p>
<p>Data on the median houseprice for different MSOAs can be downloaded from the <a href="https://www.ons.gov.uk/peoplepopulationandcommunity/housing/datasets/hpssadataset2medianhousepricebymsoaquarterlyrollingyear">ONS website</a>.</p>
<p>All the data has been pre-processed on Microsoft Excel.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./machine-learning.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Machine Learning</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./references.html" class="pagination-link">
        <span class="nav-page-text">References</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Population Science was written by Francisco Rowe, Carmen Cabrera-Arnau, Elisabetta Pietrostefani.</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">This book was built with <a href="https://quarto.org/">Quarto</a>.</div>
  </div>
</footer>



</body></html>